language: java
sudo: false
jdk:
- oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_3529ba3ea696_key -iv $encrypted_3529ba3ea696_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/b490d0b9009bba70e818
    on_success: change
    on_failure: always
    on_start: never
